version: '3'
services:
  elasticsearch:
    deploy:
      placement:
        constraints: [node.labels.number == 3]
      restart_policy:
        condition: on-failure

  mysql:
    deploy:
      placement:
        constraints: [node.labels.number == 2]
      restart_policy:
        condition: on-failure

  mongo:
    deploy:
      placement:
        constraints: [node.labels.number == 3]
      restart_policy:
        condition: on-failure

  redis:
    deploy:
      restart_policy:
        condition: on-failure

  hadoop-namenode-format:
    deploy:
      placement:
        constraints: [node.labels.number == 1]
      restart_policy:
        condition: on-failure

  hadoop-namenode:
    deploy:
      placement:
        constraints: [node.labels.number == 2]
      restart_policy:
        condition: on-failure

  hadoop-datanode:
    deploy:
      restart_policy:
        condition: on-failure

  combine-django-migration:
    deploy:
      placement:
        constraints: [node.labels.number == 1]
      restart_policy:
        condition: on-failure

  combine-django:
    deploy:
      placement:
        constraints: [node.labels.number == 1]
      restart_policy:
        condition: on-failure

  combine-celery:
    deploy:
      placement:
        constraints: [node.labels.number == 1]
      restart_policy:
        condition: on-failure

  combine-livy:
    deploy:
      placement:
        constraints: [node.labels.number == 1]
      restart_policy:
        condition: on-failure
