version: '3'
services:
  elasticsearch:
    deploy:
      placement:
        constraints: [node.labels.number == 3]
      restart: always

  mysql:
    deploy:
      placement:
        constraints: [node.labels.number == 2]
      restart: always

  mongo:
    placement:
      constraints: [node.labels.number == 3]
    restart: always

  redis:
    restart: always

  hadoop-namenode-format:
    placement:
      constraints: [node.labels.number == 1]
    restart: always

  hadoop-namenode:
    placement:
      constraints: [node.labels.number == 2]
    restart: always

  hadoop-datanode:
    restart: always

  combine-django-migration:
    placement:
      constraints: [node.labels.number == 1]
    restart: always

  combine-django:
    placement:
      constraints: [node.labels.number == 1]
    restart: always

  combine-celery:
    placement:
      constraints: [node.labels.number == 1]
    restart: always

  combine-livy:
    placement:
      constraints: [node.labels.number == 1]
    restart: always
